type: 'Task'
name: "🫠 Adhoc Request"
description: "Something unplanned that needs to skip planning queue"
title: "[AdHoc] "
labels: []
assignees: []

body:
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "Overview of the new feature and how it should help the business (the problem it is solving or the value it adds)."
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: "Business value"
      description: "How is this feature going to help the business? List value lines here."
      placeholder: |
        - %Value line 1%
        - %Value line 2%
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "What is the business acceptance criteria for this issue to be released?"
    validations:
      required: true

  - type: textarea
    id: test-cases
    attributes:
      label: "Test Cases"
      description: "🔗 Link to Test Cases PR - OR - 🥒 Gherkin syntax"

  - type: textarea
    id: risks
    attributes:
      label: "Risks / Edge Cases"
      description: "Anything that might cause delays or complications or impact other system/business functionality."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false