type: 'Task'
name: "🔧 Technical Task"
description: "A Technical task"
title: "[Task] "
labels: []
assignees: [$USER]

body:
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "Overview of the task."
    validations:
      required: true